-- Minimal SQLite schema for local development (adapted from Postgres DDL)

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS problems (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  subject TEXT NOT NULL DEFAULT 'general',
  topic TEXT,
  subtopic TEXT,
  language TEXT NOT NULL DEFAULT 'ja',
  stem TEXT NOT NULL,
  stem_latex TEXT,
  choices_json TEXT,
  answer_json TEXT,
  solution_outline TEXT,
  explanation TEXT,
  difficulty REAL,
  difficulty_level INTEGER,
  trickiness REAL,
  concepts_json TEXT,
  skill_type TEXT,
  format TEXT,
  solution_archetype TEXT,
  steps INTEGER,
  structural_sim_target REAL,
  surface_sim_target REAL,
  parameter_dof INTEGER,
  trap_type TEXT,
  wrong_patterns_json TEXT,
  context_dependency REAL,
  span_locality INTEGER,
  noise_robustness REAL,
  prerequisite_level INTEGER,
  learning_objective TEXT,
  est_time_sec INTEGER,
  source TEXT,
  source_page INTEGER,
  source_ref TEXT,
  origin TEXT NOT NULL DEFAULT 'imported',
  parent_problem_id INTEGER,
  generator TEXT,
  prompt_hash TEXT,
  generation_seed INTEGER,
  metadata TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  normalized_text TEXT,
  page INTEGER,
  answer_brief TEXT,
  references_json TEXT,
  expected_mistakes TEXT,
  confidence REAL,
  raw_text TEXT,
  raw_json TEXT,
  normalized_json TEXT,
  schema_version TEXT,
  request_id TEXT,
  final_answer_text TEXT,
  final_answer_numeric REAL,
  checks_json TEXT,
  assumptions_json TEXT,
  selected_reference_json TEXT,
  solvable INTEGER
);

CREATE INDEX IF NOT EXISTS idx_problems_difficulty ON problems(difficulty_level, difficulty, trickiness);
CREATE INDEX IF NOT EXISTS idx_problems_subject_topic ON problems(subject, topic);
CREATE INDEX IF NOT EXISTS idx_problems_origin_parent ON problems(origin, parent_problem_id);
CREATE INDEX IF NOT EXISTS idx_problems_trap ON problems(trap_type);
